WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

VIRTUAL_WIDTH = 432
VIRTUAL_HEIGHT = 243

ADV_SPEED = 25

TURBO_SPEED = 150

CAMERA_SCROLL_SPEED = 50

LAST_STATE = nil

MOUSE_TO_OBJECT_RATIOX = (love.mouse.getX() / WINDOW_WIDTH) * VIRTUAL_WIDTH
MOUSE_TO_OBJECT_RATIOY = (love.mouse.getY() / WINDOW_HEIGHT) * VIRTUAL_HEIGHT

ADV_SPRINT_SPEED = ADV_SPEED * 1.75

MAP_WIDTH = 60
MAP_HEIGHT = 60

TILE_SIZE = 16

MAPCHOSEN = 1



-- tile constants for array
WATER = 1
LEFT_ROCK_WITH_GRASS = 2
LEFT_FRONT_CORNER_ROCK_WITH_GRASS = 3
GRASS = 4
BOTTOM_RIGHT_CORNER_ROCK_WITH_GRASS = 5
RIGHT_ROCK_WITH_GRASS = 6
INSIDE_LEFT_ROCK_WITH_GRASS = 7
INSIDE_RIGHT_ROCK_WITH_GRASS = 8
TOP_LEFT_CORNER_ROCK_WITH_GRASS = 9
TOP_ROCK_WITH_GRASS = 10
BOTTOM_ROCK_WITH_GRASS = 11
TOP_RIGHT_CORNER_ROCK_WITH_GRASS = 12
MIDDLE_BRIDGE = 13
LEFT_CORNER_GRASS = 14
RIGHT_CORNER_GRASS = 15
BOTTOM_RIGHT_BRIDGE_WITH_PATH = 16
TOP_BRIDGE = 17
BOTTOM_RIGHT_BRIDGE_WITH_SAND = 18
BOTTOM_RIGHT_CORNER_BRICK_HOUSE = 19
BOTTOM_BRICK_HOUSE = 20
LEFT_SIDE_WITH_WINDOW_BRICK_HOUSE = 21
BRICKS = 22
DOOR_WITH_PATH = 23
DOOR_WITH_BALCONY_BRICK_HOUSE = 24
DOOR_WITH_BALCONY_WITH_WINDOW_BRICK_HOUSE = 25
BOTTOM_LEFT_CORNER_BRICK_HOUSE = 26
BRICKS_WTIH_WINDOW = 27
BRICKS_2 = 28
BRICKS_BALCONY_BRICK_HOUSE = 29
EDGE_ROOF_FRONT_LEFT_BRICK_HOUSE = 30
ROOF_FRONT_LEFT_BRICK_HOUSE = 31
EDGE_ROOF_LEFT_BRICK_HOUSE = 32
EDGE_ROOF_FRONT_RIGHT_BRICK_HOUSE = 33
EDGE_ROOF_RIGHT_BRICK_HOUSE = 34
ROOF_FRONT_RIGHT_BRICK_HOUSE = 35
TOP_ROOF_LEFT_BRICK_HOUSE = 36
TOP_ROOF_RIGHT_BRICK_HOUSE = 37
ROOF_LEFT_BRICK_HOUSE = 38
ROOF_RIGHT_BRICK_HOUSE = 39
ROOF_LEFT_CHIMNEY_BRICK_HOUSE = 40
ROOF_RIGHT_2_BRICK_HOUSE = 41
DOOR_BRICK_HOUSE = 42
BRICKS_2_WITH_WINDOW = 43


PATH_HORIZONTAL_TOP = 44
PATH_HORIZONTAL_BOTTOM = 45
PATH_VERTICAL = 46
PATH_HORIZONTAL_TURN_UP = 47
PATH_TO_TURN_LEFT = 48
PATH_TURN_BOTTOM_TO_RIGHT = 49
PATH_HORIZONTAL_TOP_WITH_FENCE = 50
PATH_TURN_LEFT_TO_BOTTOM = 51
TOP_LEFT_BRIDGE_POST = 52
BOTTOM_LEFT_BRIDGE_POST = 53
PATH_VERTICAL_WITH_T_AT_BOTTOM = 54
PATH_VERTICAL_TO_TURN_LEFT_AT_BOTTOM = 55
PATH_BOTTOM_TURN_FROM_TOP_TO_RIGHT = 56
PATH_BOTTOM_TURN_FROM_BOTTOM_TO_RIGHT = 57
PATH_BOTTOM_TURN_FROM_LEFT_TO_BOTTOM = 58





PATH_VERTICAL_WITH_T_AT_TOP = 67
EXTRA_PATH = 68
DIRT_TOP_WITH_GRASS = 69
DIRT_TOP_TURNING_RIGHT_WITH_GRASS = 70
DIRT_TOP_TURNING_LEFT_WITH_GRASS = 71
DIRT = 72
DIRT_WITH_RIGHT_SHADOW = 73
DIRT_WITH_LEFT_SHADOW = 74
DIRT_WITH_BOTTOM_SHADOW = 75
DIRT_WITH_BOTTOM_RIGHT_SHADOW = 76
DIRT_WITH_BOTTOM_LEFT_SHADOW = 77
DIRT_EDGE_RIGHT = 78
DIRT_EDGE_LEFT = 79
DIRT_BACK_CORNER_TURNING_LEFT = 80
DIRT_BACK_CORNER_TURNING_RIGHT = 81
RIGHT_SHADOW_FOR_DIRT = 82
TOP_SHADOW_FOR_DIRT = 83
LEFT_SHADOW_FOR_DIRT = 84
DIRT_CURVE_FROM_FRONT_TO_LEFT = 85
DIRT_BOTTOM_CORNER_TURNING_RIGHT = 86
DIRT_WITH_RIGHT_SHADOW_FOR_CORNER = 87
DIRT_TOP_WITH_GRASS_WITH_SHADOW_FOR_CORNER = 88
DIRT_BOTTOM_CORNER_TURNING_LEFT_WITH_SHADOW = 89
DIRT_WITH_LEFT_SHADOW_FOR_CORNER = 90
DIRT_TOP_WITH_GRASS_WITH_SHADOW_FOR_CORNER_ON_LEFT = 91
SHADOW_WITH_GRASS_ON_TOP_AND_RIGHT = 92
SHADOW_WITH_GRASS_ON_TOP_AND_LEFT = 93
DIRT_EDGE_LEFT_WITH_SHADOW = 94
DIRT_EDGE_RIGHT_WITH_SHADOW = 95
DIRT_TOP_CORNER_TURNING_LEFT_WITH_SHADOW = 96
PATH_T_TO_RIGHT = 97
PATH_HORIZONTAL = 98
PATH_TURNING_FROM_TOP_TO_RIGHT = 99
PATH_VERTICAL_TO_TURN_RIGHT_AT_BOTTOM = 100
PATH_TURNING_FROM_LEFT_TO_BOTTOM = 101
SAND = 102
SAND_WITH_ROCKS_AND_GRASS = 103
BRIDGE_BOTTOM_WITH_SAND = 104
BRIDGE_TOP_WITH_SAND = 105
WATER_WITH_SAND_ON_TOP = 106
SAND_WITH_ROCKS_AND_GRASS_2 = 107
WATER_WITH_SAND_ON_BOTTOM = 108
WATER_WITH_SAND_ON_RIGHT = 109
SAND_WITH_ROCKS_AND_GRASS_3 = 110
BRIDGE_TOP_RIGHT = 111
WATER_WITH_SAND_ON_TOP_2 = 112
WATER_WITH_SAND_TOP_RIGHT_CORNER = 113
WATER_WITH_SAND_ON_BOTTOM_RIGHT_CORNER= 114
WATER_WITH_SAND_ON_BOTTOM_AND_RIGHT_SIDES = 115
BRIDGE_BOTTOM_WITH_CORNER_SAND = 116
BRIDGE_TOP_WITH_CORNER_SAND = 117
FENCE = 118
FENCE_LEFT_CORNER = 119
FENCE_LEFT = 120
WOODEN_HOUSE_BOTTOM = 121
WOODEN_HOUSE_BOTTOM_LEFT_CORNER = 122
WOODEN_HOUSE_BOTTOM_RIGHT_CORNER = 123
WOODEN_HOUSE_DOOR = 124
PATH_TURNING_FROM_LEFT_TO_UP = 125
WOODEN_HOUSE_LEFT_SIDE = 126
WOODEN_HOUSE_RIGHT_SIDE = 127
WOODEN_HOUSE_WOOD = 128
WOODEN_HOUSE_UPPER_DOOR = 129
WOODEN_HOUSE_WINDOW = 130
WOODEN_HOUSE_RIGHT_EDGE_ROOF = 131
WOODEN_HOUSE_RIGHT_ROOF_FRONT = 132
WOODEN_HOUSE_LEFT_ROOF_FRONT = 133
WOODEN_HOUSE_LEFT_EDGE_ROOF = 134
WOODEN_HOUSE_UPPER_MIDDLE = 135
WOODEN_HOUSE_ROOF_APPEX = 136
WOODEN_HOUSE_RIGHT_ROOF_BACK = 137
WOODEN_HOUSE_RIGHT_ROOF_BACK_2 = 138
WOODEN_HOUSE_LEFT_ROOF_BACK = 139
WOODEN_HOUSE_LEFT_ROOF_BACK_2 = 140
WOODEN_HOUSE_RIGHT_ROOF_CORNER = 141
WOODEN_HOUSE_ROOF_AND_CHIMNEY = 142
WOODEN_HOUSE_ROOF_AND_CHIMNEY_2 = 143
CAVE_BOTTOM_LEFT_CORNER = 144
CAVE_BOTTOM_MIDDLE = 145
CAVE_BOTTOM_RIGHT_CORNER = 146
CAVE_TOP_LEFT = 147
CAVE_TOP_MIDDLE = 148
CAVE_TOP_RIGHT = 149
PATH_VERTICAL_EXTRA = 150
CAVE_TOP_SIGN = 151
CAVE_TOP_CORNER = 152
DOCK_CORNER_GOING_UP = 153
DOCK_CORNER_GOING_DOWN = 154
DOCK_RANDOM = 155
DOCK_RIGHT_RAILING = 156
DOCK = 157
DOCK_BOTTOM_RIGHT_CORNER_WITH_RAILING = 158
DOCK_TOP_RIGHT_CORNER_RAILING = 159
DOCK_WITH_WATER_TOP_RIGHT_CORNER = 160
DOCK_WITH_WATER_TOP_LEFT_CORNER = 161
DOCK_WITH_WATER_BOTTOM_RIGHT_CORNER = 162
DOCK_WITH_WATER_BOTTOM_LEFT_CORNER = 163
DOCK_LEFT_RAILING = 164
PATH_HORIZONTAL_WITH_T_GOING_UP = 165
PATH_TURNING_FROM_DOWN_TO_RIGHT = 166
FENCE_RIGHT_CORNER = 167
FENCE_RIGHT = 168
FENCE_PART = 169
TREE_TRUNK_LEFT = 170
TREETOP_MIDDLE_LEFT = 171
TREE_TRUNK_RIGHT = 172
TREETOP_MIDDLE_RIGHT = 173
TREETOP_TOP_LEFT = 174
TREETOP_TOP_RIGHT = 175
TREETOP_LEFT = 176
TREETOP_RIGHT = 177
MUD_TOP_LEFT = 178
POND_TOP_LEFT = 179
MUD_TOP_LEFT_CORNER = 180
POND_TOP_LEFT_CORNER = 181
MUD_TOP = 182
POND_TOP = 183
MUD_TOP_RIGHT = 184
POND_TOP_RIGHT = 185
MUD_TOP_RIGHT_CORNER = 186
POND_TOP_RIGHT_CORNER = 187
MUD_RIGHT = 188
POND_RIGHT = 189
MUD_BOTTOM_RIGHT = 190
POND_BOTTOM_RIGHT = 191
MUD_BOTTOM_RIGHT_CORNER = 192
POND_BOTTOM_RIGHT_CORNER = 193
MUD_BOTTOM = 194
POND_BOTTOM = 195
MUD_BOTTOM_LEFT = 196
POND_BOTTOM_LEFT = 197
MUD_BOTTOM_LEFT_CORNER = 198
POND_BOTTOM_LEFT_CORNER = 199
MUD_LEFT = 200
POND_LEFT = 201
MUD = 202
POND = 203
CAVE_EXTRA_TOP_LEFT = 204
CAVE_EXTRA_RIGHT = 205
CAVE_EXTRA_BOTTOM_RIGHT = 206
CAVE_EXTRA_TOP_RIGHT = 207
DIRT_RIGHT = 208
DIRT_BOTTOM_RIGHT = 209
DIRT_BOTTOM = 210
DIRT_BOTTOM_LEFT = 211
DIRT = 212
DIRT_BOTTOM_RIGHT_CORNER = 213
DIRT_BOTTOM_LEFT_CORNER = 214
DIRT_TOP_LEFT_CORNER = 215
DIRT_TOP_RIGHT_CORNER = 216
DIRT_LEFT = 217
DIRT_TOP_LEFT = 218
DIRT_TOP = 219
DIRT_TOP_RIGHT = 220





COLLIDABLE_TILES = {
    WATER,
    BOTTOM_ROCK_WITH_GRASS,
    LEFT_CORNER_GRASS,
    LEFT_FRONT_CORNER_ROCK_WITH_GRASS,
    BOTTOM_RIGHT_CORNER_ROCK_WITH_GRASS,
    LEFT_SIDE_WITH_WINDOW_BRICK_HOUSE,
    BRICKS,
    DOOR_WITH_BALCONY_BRICK_HOUSE,
    DOOR_WITH_BALCONY_WITH_WINDOW_BRICK_HOUSE,
    BRICKS_WTIH_WINDOW,
    BRICKS_2,
    BRICKS_BALCONY_BRICK_HOUSE,
    EDGE_ROOF_FRONT_LEFT_BRICK_HOUSE,
    ROOF_FRONT_LEFT_BRICK_HOUSE,
    EDGE_ROOF_LEFT_BRICK_HOUSE,
    EDGE_ROOF_FRONT_RIGHT_BRICK_HOUSE,
    EDGE_ROOF_RIGHT_BRICK_HOUSE,
    ROOF_FRONT_RIGHT_BRICK_HOUSE,
    TOP_ROOF_LEFT_BRICK_HOUSE,
    TOP_ROOF_RIGHT_BRICK_HOUSE,
    ROOF_LEFT_BRICK_HOUSE,
    ROOF_RIGHT_BRICK_HOUSE,
    ROOF_LEFT_CHIMNEY_BRICK_HOUSE,
    ROOF_RIGHT_2_BRICK_HOUSE,
    DOOR_BRICK_HOUSE,
    BRICKS_2_WITH_WINDOW,
    TREE_TRUNK_LEFT,
    TREETOP_MIDDLE_LEFT,
    TREE_TRUNK_RIGHT,
    TREETOP_MIDDLE_RIGHT,
    TREETOP_TOP_LEFT,
    TREETOP_TOP_RIGHT,
    TREETOP_LEFT,
    TREETOP_RIGHT,
    DIRT_EDGE_RIGHT,
    DIRT_EDGE_LEFT,
    DIRT_BOTTOM_CORNER_TURNING_LEFT_WITH_SHADOW,
    DIRT_BOTTOM_CORNER_TURNING_RIGHT,
    DIRT_TOP_WITH_GRASS_WITH_SHADOW_FOR_CORNER,
    DIRT_TOP_WITH_GRASS_WITH_SHADOW_FOR_CORNER_ON_LEFT,
    DIRT_TOP_WITH_GRASS,
    DIRT_TOP_TURNING_RIGHT_WITH_GRASS,
    DIRT_TOP_TURNING_LEFT_WITH_GRASS,
    DIRT_WITH_BOTTOM_SHADOW,
    DIRT_WITH_BOTTOM_RIGHT_SHADOW,
    DIRT_WITH_BOTTOM_LEFT_SHADOW

}

HOUSETILES = {
  DOOR_WITH_PATH
}

CAVETILES = {
  CAVE_BOTTOM_MIDDLE,
  CAVE_BOTTOM_LEFT_CORNER,
  CAVE_BOTTOM_RIGHT_CORNER,
  CAVE_TOP_LEFT,
  CAVE_TOP_SIGN,
  CAVE_TOP_MIDDLE,
  CAVE_TOP_RIGHT
}

FISHINGDOCK = {
  DOCK,
  DOCK_WITH_WATER_TOP_LEFT_CORNER_RAILING,
  DOCK_WITH_WATER_BOTTOM_LEFT_CORNER
}
